language: node_js
node_js:
  - "node"
warnings_are_errors: false
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  project: ./build/
  commit_message: "Deploy release ${TRAVIS_TAG}"
on:
  branch: master
